### ISSUE TITLE
Error in FUN(X[[i]], ...) : object '.group' not found

### ISSUE THREAD

**Issue by guivivi** [business-science/anomalize#2] opened 2018-04-09 13:28 UTC
Hello,

Thanks for this outstanding group.

Following the code posted in https://business-science.github.io/anomalize/ I have got this error:
tidyverse_cran_downloads %>%
     # Data Manipulation / Anomaly Detection
     time_decompose(count, method = "stl") %>%
     anomalize(remainder, method = "iqr") %>%
     time_recompose() %>%
     # Anomaly Visualization
     plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.25)
Error in FUN(X[[i]], ...) : object '.group' not found

Is there any way to overcome this error?

Thanks in advance.

Kind regards,

Guillermo

**Comment by mdancho84** [comment] 2018-04-09 16:46
Where is the function failing? Please go through each of the steps one by one. and let me know which function the error occurs at.

**Comment by JoeFernando** [comment] 2018-04-09 23:13
I get he same error. The problem is with the viz part of the code:
`plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.25)`

Reinstalled `tibbletime` and result was the same

**Comment by JoeFernando** [comment] 2018-04-10 03:07
So Davis, how to solve this problem.....any ideas?
Keen to try out a few ideas

**Comment by mdancho84** [comment] 2018-04-11 16:28
We've been hearing of a number of errors that are all related to old versions of various packages that `anomalize` depends on. Try updating your packages and see if it fixes the situation. Please let us know if it does.

**Comment by mdancho84** [comment] 2018-04-11 19:15
This should be fixed now. Can someone that had the problem please confirm?

**Comment by JoeFernando** [comment] 2018-04-11 23:17
Worked!!! Reinstalled the github version. Thank you so much for this, loving it!

**Comment by mdancho84** [comment] 2018-04-11 23:51
Niiiiice! Great work @MartenMM!

**Closed by mdancho84** 2018-04-11 23:51 UTC

**Comment by MartenMM** [comment] 2018-04-12 04:27
Yay! My first accepted PR :-)

**Comment by guivivi** [comment] 2018-04-12 08:15
After reinstalling the github version it also works for me, many thanks!!
